version: "3.8"
services:
  backend:
    image: registry.example.com/yourorg/auto-backend:release
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres

  frontend:
    image: registry.example.com/yourorg/auto-frontend:release
    env_file:
      - .env.prod
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  # DB/Minio/Redis en producción pueden ser servicios gestionados (RDS, ElastiCache, S3).
  # Si los ejecutas con Docker en el mismo host, puedes incluirlos aquí (como en base).
