version: "3.8"

services:
  backend:
    image: autoya-backend:prod
    container_name: autoya-backend-prod
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - postgres-prod
      - redis-prod
      - minio-prod

  frontend:
    image: autoya-frontend:prod
    container_name: autoya-frontend-prod
    ports:
      - "80:80"
    env_file:
      - .env.prod
    restart: always
    depends_on:
      - backend

  postgres-prod:
    image: postgres:15
    container_name: postgres-prod
    environment:
      POSTGRES_USER: autoya
      POSTGRES_PASSWORD: super-secret-pass
      POSTGRES_DB: autoya_prod
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis-prod:
    image: redis:7
    container_name: redis-prod
    ports:
      - "6381:6379"
    volumes:
      - redis_data_prod:/data

  minio-prod:
    image: quay.io/minio/minio:latest
    container_name: minio-prod
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9004:9000"  # API
      - "9005:9001"  # Consola web
    volumes:
      - minio_data_prod:/data

volumes:
  postgres_data_prod:
  redis_data_prod:
  minio_data_prod:
