server:
  port: 8081
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

spring:
  application:
    name: auth-service

  messages:
    basename: messages
    encoding: UTF-8

  web:
    locale: es
    locale-resolver: fixed

  datasource:
    url: jdbc:postgresql://localhost:5432/autoya_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 120000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      username: default   # si tu redis requiere usuario (Redis 6+ ACL)
      password:           # deja vacío si no usas password
      database: 0
      timeout: 60s
      connect-timeout: 2s

  cache:
    type: redis
    redis:
      time-to-live: 3600s
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "autoya::"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha

# ===============================
# MINIO CONFIGURATION
# ===============================
minio:
  endpoint: http://localhost:9000
  access-key: tu_minio_access_key
  secret-key: tu_minio_secret_key
  bucket-name: autoya-bucket
  region: us-east-1
  secure: false

# ===============================
# CORS CONFIGURATION
# ===============================
cors:
  allowed-origins: "http://localhost:3000,http://localhost:4200"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# ===============================
# APPLICATION SPECIFIC CONFIGURATION
# ===============================
app:
  email:
    host: smtp.gmail.com
    port: 587
    username: tu_email@gmail.com
    password: tu_email_password
    from: autoya.noreply@gmail.com

  reservation:
    max-days: 30
    min-hours-notice: 2
    cancellation-hours: 24

  payment:
    mock-enabled: true
    currency: COP
    tax-rate: 0.19

  notification:
    email-enabled: true
    sms-enabled: false
    push-enabled: false

# ===============================
# JWT CONFIGURATION
# ===============================
jwt:
  secret: Z3NqZGprbGhzamtsZGhzamtsZGhzamtsZGhzamtsZGhzamtsZGhz
